[package]
name = "scanner_controller"
version = "0.1.0"
edition = "2021"
# build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.5"
pdf-writer = "0.6.0"
sane-scan = "0.1.2"
